using UnityEngine;
using System.Collections;

public class gunMover : MonoBehaviour {

    /// <summary>
    /// sensibility of moving
    /// </summary>
    public float speed;

	// Update is called once per frame
	void FixedUpdate ()
    {
        //I memorize the offset generated by pressing the key (W-A-S-D or arrows)
        float moveForward = Input.GetAxis("Vertical");
        float moveBackward = -Input.GetAxis("Horizontal");

        //debug
        if (moveForward != 0 || moveForward != 0)
        {
            Debug.Log("for: " + moveForward);
            Debug.Log("back: " + moveBackward);
        }

        ///Create the vector3 generated by the offset before
        Vector3 v3 = new Vector3(moveForward, 0.0f, moveBackward);

        ///apply the vector 3 summed with the previous values of the gun's transform at the transform
        transform.position = new Vector3(transform.position.x + moveForward,
           transform.position.y, transform.position.z + moveBackward);
    }
}
